package at.minecraft.pugna.chat;

public enum Message {
    /* === General === */
    INVALID_USAGE,
    NO_PERMISSION,
    PLAYER_ONLY_COMMAND,

    /* === Countdown === */
    COUNTDOWN_USAGE,
    COUNTDOWN_INVALID_NUMBER,
    COUNTDOWN_NOT_ACTIVE,
    COUNTDOWN_UPDATE_SUCCESS,

    /* === Hub === */
    HUB_KICK,

    /* === Team === */
    TEAM_USAGE,
    NO_TEAM,
    TEAM_JOIN_HINT,
    TEAM_RENAME_HINT,

    TEAM_LIST_HEADER,
    TEAM_LIST_ENTRY,
    TEAM_LIST_EMPTY,

    TEAM_JOIN_NOT_FOUND,
    TEAM_JOIN_SAME_TEAM,
    TEAM_JOIN_FULL,
    TEAM_JOIN_SELF,
    TEAM_JOIN_OTHERS,

    TEAM_LEAVE_SELF,
    TEAM_LEAVE_OTHERS,

    TEAM_RENAME_INVALID,
    TEAM_RENAME_SAME_NAME,
    TEAM_RENAME_TAKEN,
    TEAM_RENAME_SUCCESS,

    TEAM_ASSIGNED,
    TEAM_NOT_ASSIGNED,
    TEAM_TELEPORT,
    TEAM_ELIMINATED,
    TEAM_WIN,

    /* === Player === */
    PLAYER_JOIN,
    PLAYER_QUIT,
    PLAYER_DEATH_SELF,
    PLAYER_DEATH_OTHERS,
    PLAYER_KILL_SELF,
    PLAYER_KILL_OTHERS,
    PLAYER_WIN,

    /* === Phases === */
    TELEPORT_COUNTDOWN,
    TELEPORT_COUNTDOWN_ABORTED,

    GAME_START_COUNTDOWN,
    GAME_START,
    GAME_PAUSED,
    GAME_RESUMED,

    NETHER_TELEPORT_NOT_ALLOWED,
    NETHER_PORTAL_BLOCK_MODIFICATION,
    NETHER_START,

    BORDER_SHRINK_COUNTDOWN,
    BORDER_SHRINK_START,
    BORDER_SHRINK_END,

    NETHER_END_COUNTDOWN,
    NETHER_END,

    ENEMY_REVEAL_COUNTDOWN,
    ENEMY_REVEAL,
    ENEMY_REVEAL_NO_ENEMY,

    GAME_END_COUNTDOWN,
    GAME_END_EXPLANATION,
    GAME_END_NO_WINNER,

    SERVER_RESTART_COUNTDOWN,

    /* === Server === */
    KICK_SERVER_FULL,
    KICK_SERVER_RESTARTING
}
