package at.minecraft.pugna.chat;

public enum Message {
    /* === General === */
    INVALID_USAGE,
    NO_PERMISSION,
    PLAYERS_ONLY_COMMAND,
    INVALID_NUMBER,
    NO_TEAM,

    /* === Countdown === */
    COUNTDOWN_USAGE,
    COUNTDOWN_NOT_ACTIVE,
    COUNTDOWN_UPDATE_SUCCESS,

    /* === GUI === */
    GUI_USAGE,
    GUI_ENABLED,
    GUI_DISABLED,

    /* === Rules === */
    RULES_USAGE,
    RULES_ITEMS,
    RULES_ENCHANTMENTS,
    RULES_POTIONS,

    /* === Team === */
    TEAM_USAGE,
    TEAM_JOIN_HINT,
    TEAM_RENAME_HINT,

    TEAM_LIST_HEADER,
    TEAM_LIST_ENTRY,
    TEAM_LIST_EMPTY,

    TEAM_JOIN_NOT_ALLOWED,
    TEAM_JOIN_NOT_FOUND,
    TEAM_JOIN_SAME_TEAM,
    TEAM_JOIN_FULL,
    TEAM_JOIN_SELF,
    TEAM_JOIN_OTHERS,

    TEAM_LEAVE_NOT_ALLOWED,
    TEAM_LEAVE_SELF,
    TEAM_LEAVE_OTHERS,

    TEAM_RENAME_NOT_ALLOWED,
    TEAM_RENAME_INVALID,
    TEAM_RENAME_SAME_NAME,
    TEAM_RENAME_TAKEN,
    TEAM_RENAME_SUCCESS,

    TEAM_ASSIGNED,
    TEAM_NOT_ASSIGNED,

    TEAM_TELEPORT,
    TEAM_ELIMINATED,
    TEAM_WIN,

    /* === Player === */
    PLAYER_JOIN,
    PLAYER_QUIT,

    PLAYER_DEATH_SELF,
    PLAYER_DEATH_OTHERS,
    PLAYER_KILLED_SELF,
    PLAYER_KILLED_OTHERS,

    PLAYER_WIN,

    /* === Phases === */
    TELEPORT_COUNTDOWN,
    TELEPORT_COUNTDOWN_ABORTED,

    GAME_START_COUNTDOWN,
    GAME_START,
    GAME_PAUSED,
    GAME_RESUMED,

    FOUND_DIAMONDS,
    FORBIDDEN_ITEMS_REMOVED,

    NETHER_TELEPORT_NOT_ALLOWED,
    NETHER_PORTAL_BLOCK_MODIFICATION_NOT_ALLOWED,
    NETHER_START_COUNTDOWN,
    NETHER_START,
    NETHER_END_COUNTDOWN,
    NETHER_END,

    BORDER_SHRINK_START_COUNTDOWN,
    BORDER_SHRINK_START,
    BORDER_SHRINK_END,

    ENEMY_REVEAL_COUNTDOWN,
    ENEMY_REVEAL_SUCCESS,
    ENEMY_REVEAL_NO_ENEMY_FOUND,

    GAME_END_COUNTDOWN,
    GAME_END_EXPLANATION,
    GAME_END_NO_WINNER,

    SERVER_RESTART_COUNTDOWN,

    /* === Kick === */
    KICK_SERVER_FULL,
    KICK_HUB_COMMAND,
    KICK_PLAYTIME_WINDOW,
    KICK_SERVER_RESTARTING
}
