name: Pugna
version: '1.0'
main: at.minecraft.pugna.Pugna
authors: [ DerStresser ]
commands:
  countdown:
    description: "Allows you to change the countdown seconds."
  gui:
    description: "Lets you enable/disable the gui."
  hub:
    description: "Lets you leave the server."
  team:
    description: "Basic team commands (list/join/rename/leave)."