game:
  development: false
  development_seed:
    seed: null
    world_type: "NORMAL"
  playtime:
    start: "00:00:00"
    end: "00:00:00"
    timezone: "Europe/Vienna"
  require_majority_online: true
  use_friedolin: true
  use_berta: true
  use_found_diamonds: true

players:
  comments: "Maximum of 128 players in total"
  friendly_fire: false
  max_teams_count: 16
  max_team_capacity: 1
  min_players_count: 2
  default_team_names: [
    "Abriss", "AimAssist", "AimBot", "Alpha", "ArrowStorm", "AutoKlicker",
    "BlitzGang", "BlockHitters", "Blocklords", "BowLegends", "BowSpammer", "Bravo",
    "Campers", "Chaos", "ChickenKillers", "Clowns", "ComboGods", "CritCrew", "CritHit", "Critters",
    "Delta", "DoubleHit", "Draufgaenger", "Drescher",
    "Echo", "EliteForce", "eZClap", "eZWin",
    "Farmers", "FastClick", "FirstBlood", "FirstKill", "FlameBros",
    "Gapplers", "GGWP", "GIGA", "GOATs", "Griefer",
    "HackClient", "Hackers", "HauDrauf", "Headshot", "Hunters",
    "Inferno", "IronGang", "Irre",
    "JavaEdition", "JavaScript", "Juergen",
    "Killaura", "KillStreak", "Klatsche", "KlickSpeed", "Knockback",
    "Laggers", "Lappen", "LavaBoys", "LowPingers", "Lustknaben",
    "MelonGang", "MineBoys", "MongoBongo", "MultiKill",
    "Nodus", "NoHacks", "Noobs", "NoSkill",
    "OhnePlan", "Ohrfeige", "OPGang", "Overkill",
    "Phantom", "Ping999", "PixelCrew", "PotatoArmy", "Pruegler", "PvPGoetter",
    "QuadForce", "Quatschkoepfe", "QuickScope",
    "RageMode", "Rasur", "Rekt", "RiskTakers", "RodGods",
    "Schnetzler", "Shadow", "Skillaura", "SkullCrush", "SpawnTrap", "SpeedHit", "Storm", "Sweat99", "SwordMania", "SwordZ",
    "TeamKill", "TeamOP", "Terror", "Titan", "TNTGang", "TNTKings", "TNTLegends", "TrapMasters", "TryHard",
    "Ultra", "Unfall", "UnitZ", "Unkillable", "Unstoppables",
    "VARO", "VaroBoys", "Verpeilt", "VoidRiders",
    "Warriors", "Watsche", "WinOrDie", "WomboCombo",
    "Xplosion", "XRay", "Xtreme",
    "YEET", "YOLO",
    "Zerstampfer", "Zerstoerer", "Zucker"
  ]

lobby:
  world: "lobby"
  spawn:
    x: 0.5
    y: 64.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0

pugna:
  world: "pugna"
  nether_world: "pugna_nether"
  spawn:
    x: 0.5
    # y will be calculated automatically
    z: 0.5
    yaw: 0.0
    pitch: 0.0
  seeds:
    comments: [
      "world_types: NORMAL | LARGE_BIOMES",
      "radius depends on player count: 4 players -> 24 blocks | 8 players -> 32 blocks | 16 players -> 40 blocks | 32 players -> 48 blocks | 64 players -> 56 blocks | 128 players -> 64 blocks"
    ]
    entries:
      0:
        seed: -9008001471532830816
        world_type: "NORMAL"
        min_player_count: 4
        max_player_count: 16
      1:
        seed: -7369099047549311069
        world_type: "NORMAL"
        min_player_count: 4
        max_player_count: 32
      2:
        seed: -1124061784166597672
        world_type: "LARGE_BIOMES"
        min_player_count: 4
        max_player_count: 32
      3:
        seed: 14000054
        world_type: "NORMAL"
        min_player_count: 4
        max_player_count: 16
      4:
        seed: 1729687638268160097
        world_type: "NORMAL"
        min_player_count: 4
        max_player_count: 16
      5:
        seed: 174001683
        world_type: "NORMAL"
        min_player_count: 8
        max_player_count: 16
      6:
        seed: 2078843530080609644
        world_type: "NORMAL"
        min_player_count: 4
        max_player_count: 128
      7:
        seed: 323003467
        world_type: "NORMAL"
        min_player_count: 4
        max_player_count: 64
      8:
        seed: 527616680074691
        world_type: "NORMAL"
        min_player_count: 4
        max_player_count: 64
      9:
        seed: 728006554
        world_type: "NORMAL"
        min_player_count: 4
        max_player_count: 16
      10:
        seed: 762008129
        world_type: "NORMAL"
        min_player_count: 4
        max_player_count: 32

border:
  base_size: 2048.0
  end_size: 256.0
  max_size: 4096.0
  size_per_player: 64.0

countdowns:
  lobby:
    seconds: 60
  game:
    seconds: 40
  restart:
    seconds: 25

events:
  nether_start:
    enabled: true
    countdown_start_seconds: 3600     # 01:00:00
    event_seconds: 5400               # 01:30:00
  border_shrink:
    enabled: true
    countdown_start_seconds: 12600    # 03:30:00
    event_start_seconds: 14400        # 04:00:00
    event_end_seconds: 36000          # 10:00:00
  nether_end:
    enabled: true
    countdown_start_seconds: 41400    # 11:30:00
    event_seconds: 43200              # 12:00:00
  enemy_reveal:
    enabled: true
    countdown_start_seconds: 48600    # 13:30:00
    event_seconds: 50400              # 14:00:00
  game_end:
    countdown_start_seconds: 55800    # 15:30:00
    event_seconds: 57600              # 16:00:00

item_names:
  team_selection_item: "§aTeam-Auswahl§r"
  info_book_item: "§6Pugna"
  navigation_item: "§6Navigation§r"
  leave_item: "§cVerlassen§r"